UI smoke tests v.2.4

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -39,8 +39,37 @@ jobs:
       - name: Build with Docker Compose
         run: docker-compose build
 
-      - name: Start Docker Compose services
-        run: docker-compose up
+      - name: Start Docker Compose services in background
+        run: docker-compose up -d
+
+      - name: Wait for Selenium to be ready
+        run: |
+          echo "Waiting for Selenium to start..."
+          for i in {1..10}; do
+            if curl -sSL "http://localhost:4444/wd/hub/status" 2>&1 | grep -q '"ready": true'; then
+              echo "Selenium is ready!"
+              exit 0
+            fi
+            echo "Waiting for Selenium... Attempt $i"
+            sleep 5
+          done
+          echo "Selenium failed to start within the allotted time"
+          exit 1
+
+      - name: Maven test
+        run: mvn test
+        env:
+          CHROME_OPTIONS: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
+          CI_RUN: true
+          SELENIUM_HUB_URL: http://localhost:4444/wd/hub
+
+      - name: Chrome test
+        if: always()
+        run: mvn test
+        env:
+          CHROME_OPTIONS: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
+          CI_RUN: true
+          SELENIUM_HUB_URL: http://localhost:4444/wd/hub
 
       - name: Attach screenshots
         if: failure()
